# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Minima"
license = "MIT"
licenselink = "https://github.com/mivinci/minima/blob/master/LICENSE"
description = "A Hugo port of Hexo Minima"
homepage = "https://github.com/mivinci/hugo-theme-minima"
tags = ["minimal", "clean", "blog", "responsive", "personal", "simple", "minimalist", "portfolio", "dark"]
features = ["Dark mode", "KaTeX", "Mermaid", "VSCode-style code highlighting", "External link post"]
min_version = "0.41.0"

[author]
  name = "XJJ"
  homepage = "https://xjj.pub"

# If porting an existing theme
[original]
  name = "Minima"
  homepage = "https://adisaktijrs.github.io/minima"
  repo = "https://github.com/adisaktijrs/hexo-theme-minima"
